#!/bin/bash
#set -x

COMMAND="$1"
CONFIG_FILE="./ec2config"
USERDATA_FILE="./userdata"
HELP_STRING="Usage: $(basename $0) [up|halt|reboot|destroy|ssh|status|status-all]\n
                  \tFile ./ec2config is mandatory. File ./userdata - optional." 


# Check if the ec2config file exists
if [ ! -f "$CONFIG_FILE" ]; then
  echo "The ec2config file does not exist."
  exit 1
fi

# Read variables from ec2config
while IFS= read -r line; do
  # Remove everything after the first '#' to ignore comments
  line="$(echo ${line%%#*} | tr -d '"')"
  # Skip empty lines
  [[ -z "$line" ]] && continue
  # Split the line by '=' and set the variable
  IFS="=" read -r var value <<< "$line"
  export $var=$value
done < "$CONFIG_FILE"


# Check if the required command-line arguments are provided
if [ $# -lt 1 ]; then
  echo -e $HELP_STRING
  exit 2
fi

case $COMMAND in
  up)
    # Check if an instance with the given tag already exists
     EXISTING_INSTANCE=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                             "Name=instance-state-name,Values=running,pending,stopped" \
                             --query 'Reservations[].Instances[0].InstanceId' --output text)
    if [ -n "$EXISTING_INSTANCE" ]; then
      # If an instance with the given tag exists, start it
      aws ec2 start-instances --instance-ids "$EXISTING_INSTANCE"
    else
      # If no instance with the given tag exists, create a new one with or w/o user data
        if [ -r "$USERDATA_FILE" ]; then
          # Use user data file if present
          aws ec2 run-instances --image-id $AMI --instance-type t2.micro --subnet-id $SUBNET \
                        --security-group-ids $SG --key-name $KEY_PAIR \
                        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$TAG}]" \
                        --user-data file://$USERDATA_FILE
        else
          # Run instance w/o user data
          aws ec2 run-instances --image-id $AMI --instance-type t2.micro --subnet-id $SUBNET \
                        --security-group-ids $SG --key-name $KEY_PAIR \
                        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$TAG}]"
      fi
    fi
    ;;

  halt)
    # Stop an EC2 instance
    INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                             "Name=instance-state-name,Values=running,pending" \
                             --query 'Reservations[].Instances[0].InstanceId' --output text)
    aws ec2 stop-instances --instance-ids $INSTANCE_ID
    ;;

  reboot)
    # Reboot an EC2 instance
    INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                             "Name=instance-state-name,Values=running" \
                             --query 'Reservations[].Instances[0].InstanceId' --output text)

    aws ec2 reboot-instances --instance-ids $INSTANCE_ID
    ;;

  destroy)
    # Terminate an EC2 instance
    INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                             "Name=instance-state-name,Values=running,pending,stopped" \
                             --query 'Reservations[].Instances[0].InstanceId' --output text)

    aws ec2 terminate-instances --instance-ids $INSTANCE_ID
    ;;

  ssh)
    # SSH into an EC2 instance
    
    PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                    "Name=instance-state-name,Values=running" \
                    --query 'Reservations[].Instances[0].PublicIpAddress' --output text)
    if [ -z "$PUBLIC_IP" ]; then
      echo "Instance not_found/pending/down or does not have a public IP."
      exit 1
    fi
    ssh -i "$SSH_KEY_FILE" -o StrictHostKeyChecking=no $SSH_USER@$PUBLIC_IP
    ;;

  status)
    # View the status of an EC2 instance by tag
    STATUS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$TAG" \
                     --query 'Reservations[].Instances[0].State.Name' --output text)
    echo "Instance(s) '$TAG' status is: $STATUS"
    ;;

  status-all)
    # View the status of all instances with their instance ID and external IP
    INSTANCES=$(aws ec2 describe-instances --query 'Reservations[].Instances')
    if [ -z "$INSTANCES" ]; then
      echo "No instances found."
      exit 2
    fi
    echo "$INSTANCES" | \
         jq -r '.[][] | "\(.Tags[0].Value)\t\t\(.State.Name)\t\(.InstanceId)\t\(.PublicIpAddress)"'
    ;;

  *)
    echo "Invalid command: $COMMAND"
    echo -e $HELP_STRING
    exit 1
    ;;
esac
